const planoDie1 = "O Plano Dietético Personalizado ou Plano Alimentar consiste numa série de orientações, recomendações sobre alimentação e cardápio elaborado especialmente para a necessidade de cada indivíduo com base na avaliação antropométrica e demais exames realizados previamente."

const planoDie2 = "Importante enfatizar que o Plano Alimentar é individual e intransferível, ou seja, é preparado para o perfil de cada pessoa, desta forma o plano alimentar não deve ser passado a outra pessoa. Você não deve copiar um Plano Nutricional de um amigo ou conhecido, pois ele foi preparado para as necessidades específicas dele e não suas. Há uma série de fatores importantes que devem ser consideradas, inclusive a suplementação de determinados minerais, vitaminas e outras substâncias. Por isso cada plano é pessoal e intransferível."

const nutriçao = "O controle de peso é um processo sistêmico que envolve uma série de diferentes fatores. Controlar o peso de uma pessoa envolve estabelecer uma estratégia equilibrada e efetiva para um estilo de vida saudável, incluindo a nutrição, as atividades e o apoio externo. Além de necessitar mecanismos para conseguir um feedback apropriado e criar responsabilidade para as ações da pessoa, a estratégia para um controle de peso efetivo inclui um plano de nutrição, um plano de atividades, apoio do grupo e um conjunto de ferramentas efetivas para fazer as mudanças apropriadas nos hábitos alimentares e em outros comportamentos associados ao peso."

const reed1 = "A reeducação alimentar é um processo de aprendizagem e de mudança comportamental exercido por meio de orientações nutricionais específicas em que o indivíduo conhece e incorpora hábitos alimentares saudáveis."

const reed2 = "A educação é muito mais que instrução. É um processo que deve ser criado entre educador e educando, tendo como objetivo a construção do conhecimento, seja ele qual for, sobre português, matemática, história e porque não, nutrição."

const reed3 = "Enquanto nas dietas não ocorrem mudanças internas, e ao fim de cada uma, as pessoas voltam aos antigos hábitos, na reeducação alimentar as mudanças acontecem de forma tão profunda que se tornam parte do indivíduo."

const reed4 = "Por se tratar de um processo de aprendizagem, o paciente, no final do tratamento, torna-se apto a escolher corretamente os alimentos, tanto no aspecto qualitativo quanto no quantitativo, sem deixar de incluir o que faz parte da sua própria cultura."

const reed5 = "A reeducação alimentar pode ter vários objetivos: perda ou ganho de peso, controle do colesterol, da glicose ou até de inúmeras outras doenças e situações que exigem uma mudança na alimentação, como por exemplo, a cirurgia bariátrica. Mesmo que você esteja ‘super saudável’ e queira apenas manter o peso, a reeducação alimentar é fundamental, pois hoje já temos total certeza da importância da nutrição no bem-estar e na qualidade de vida."

const personal = "Personal diet tem como significado Assistência Nutricional Global Personalizada, sendo um programa completo de serviços nutricionais o qual envolve atendimento clínico, programas de emagrecimento, ganho de massa corporal, projeto de qualidade de vida, planejamento de refeições práticas, técnicas dietéticas e de segurança, higiene alimentar, receitas saudáveis, arrumação da cozinha, do estoque e geladeira, inclui também lista de compras e acompanhamento ao supermercado. Ou seja, é um serviço nutricional completo e totalmente personalizado. Trata-se de um programa personalizado, realizado em domicílio abrangendo toda a família."

const acom = "Cuidados de nutrição ideais envolvem um cronograma contínuo desde o pré-operatório até o período pós-operatório. A maior ênfase na preparação pré-operatória de cirurgia metabólica é otimizar o estado de saúde reduzindo assim risco de infecção, complicações e tempo de internação. No pré-operatório a ênfase do tratamento nutricional é dada ao início do processo de reeducação alimentar e à conscientização do paciente sobre a importância destas mudanças e do acompanhamento nutricional no pós-operatório, para redução os riscos de complicações nutricionais inerentes à cirurgia. Quando indicado, neste momento pode ser iniciada uma terapia nutricional para perda de peso pré-operatória ou para correção de deficiências nutricionais pré-existentes, decorrentes de alimentação inadequada. No pós-operatório o acompanhamento nutricional deve ser frequente e em longo prazo."

export { planoDie1, planoDie2, nutriçao, reed1, reed2, reed3, reed4, reed5, personal, acom }